source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.3"

gem "aws-sdk-rails"
gem "aws-sdk-ses"
gem "bcrypt"
gem "bootsnap", require: false
gem "brakeman"
gem "dotenv-rails"
gem "factory_bot_rails"
gem "faker"
gem "friendly_id"
gem "heroicon"
gem "http_accept_language"
gem "jsbundling-rails"
gem "messagebird-rest", require: "messagebird"
gem "normailize"
gem "pg"
gem "phonelib"
gem "prettier"
gem "propshaft"
gem "puma"
gem "pundit"
gem "rails"
gem "rails-i18n"
gem "rails_12factor"
gem "rspec-rails"
gem "sentry-rails"
gem "sentry-ruby"
gem "sidekiq"
gem "slim-rails"
gem "standard"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "template-ruby"
gem "turbo-rails"
