source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.3"

gem "aws-sdk-rails"
gem "aws-sdk-s3", require: false
gem "aws-sdk-ses"
gem "bcrypt"
gem "bootsnap", require: false
gem "brakeman"
gem "capybara"
gem "dotenv-rails"
gem "factory_bot_rails"
gem "faker"
gem "friendly_id"
gem "heroicon"
gem "http_accept_language"
gem "image_processing"
gem "jsbundling-rails"
gem "kaminari"
gem "letter_opener", group: :development
gem "messagebird-rest", require: "messagebird"
gem "money-rails"
gem "normailize"
gem "omniauth"
gem "omniauth-facebook"
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"
gem "parity"
gem "pg"
gem "phonelib"
gem "prettier"
gem "propshaft"
gem "pry-rescue"
gem "public_suffix"
gem "puma"
gem "pundit"
gem "rails"
gem "rails-i18n"
gem "redis"
gem "rspec-rails"
gem "sentry-rails"
gem "sentry-ruby"
gem "sidekiq"
gem "sidekiq-cron"
gem "slim-rails"
gem "sprockets"
gem "standard"
gem "stimulus-rails"
gem "stripe"
gem "tailwindcss-rails"
gem "template-ruby"
gem "turbo-rails"
gem "twitter"
gem "webdrivers"
