development:
  adapter: postgresql
  encoding: unicode
  database: pipelines_development

test:
  adapter: postgresql
  encoding: unicode
  database: pipelines_test

production:
  adapter: postgresql
  encoding: unicode
  database: pipelines_production
