ProcessPipelinesJob:
  cron: "*/5 * * * *"
  class: ProcessPipelinesJob

SendHourlyEmailDigestsJob:
  cron: "0 * * * *"
  class: "SendHourlyEmailDigestsJob"

SendDailyEmailDigestsJob:
  cron: "0 * * * *"
  class: "SendDailyEmailDigestsJob"

SendWeeklyEmailDigestsJob:
  cron: "0 * * * *"
  class: "SendWeeklyEmailDigestsJob"

SendMonthlyEmailDigestsJob:
  cron: "0 * * * *"
  class: "SendMonthlyEmailDigestsJob"
