name: Tests
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_USER: pipelines
          POSTGRES_DB: pipelines_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Setup Pipelines
        run: bin/setup
      - run: bundle exec rspec
